---
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: '070421'
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  use-host: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  nameserver:
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  fallback:
  - 1.0.0.1
  - 1.1.1.1
  - 8.8.4.4
  default-nameserver:
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "*.google.com"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - time-ios.apple.com
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - "+.qq.com"
  - "+.tencent.com"
  - "*.n.n.srv.nintendo.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - "+.stun.*.*.*.*.*"
  - na.b.g-tun.com
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - shark007.net
  - Mijia Cloud
  - "+.cmbchina.com"
  - "+.cmbimg.com"
  - local.adguard.org
  - "+.sandai.net"
  - "+.n0808.com"
  - "+.dns.google"
proxies:
- name: vmess_tcp_tls
  server: 103.163.xx.xx
  port: 443
  type: vmess
  uuid: 14eaa7c4-e4b7-xxxx-xxxx-5e35d38bb763
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: http
  http-opts:
    method: GET
    path:
    - "/vmess-tcp"
    headers:
      Host:
      - bug.com
  udp: true
- name: vmess_ws_tls
  server: 103.163.xx.xx
  port: 443
  type: vmess
  uuid: 14eaa7c4-e4b7-xxxx-xxxx-5e35d38bb763
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: "/vmess-ws"
    headers:
      Host: bug.com
  udp: true
- name: vmess_grpc_tls
  server: 103.163.xx.xx
  port: 443
  type: vmess
  uuid: 14eaa7c4-e4b7-xxxx-xxxx-5e35d38bb763
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: grpc
  servername: awscdn-bytedance.bug.com
  grpc-opts:
    grpc-mode: none
    grpc-service-name: vmess-grpc
  udp: true
- name: rmtj_trojan
  server: 103.227.xxx.xxx
  port: 443
  type: trojan
  password: 30052020
  sni: akmtest.bug.com
  skip-cert-verify: true
  udp: true
- name: rmtj_trojan_grpc
  server: 103.227.xxx.xxx
  port: 443
  type: trojan
  password: 30052020
  sni: akmweb.youngjoygame.com
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-mode: gun
    grpc-service-name: trojan-grpc
  udp: true
- name: rmtj_trojan_ws
  server: 103.227.xxx.xxx
  port: 443
  type: trojan
  password: 30052020
  sni: awscdn-avatar.bug.com
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: "/trojan-ws"
    headers:
      Host: 103.227.xxx.xxx
  udp: true
proxy-groups:
- name: GLOBAL
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 200
  tolerance: 5
  proxies:
  - vmess_tcp_tls
  - vmess_ws_tls
  - vmess_grpc_tls
- name: BEST-PING
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 200
  tolerance: 5
  proxies:
  - rmtj_trojan
  - rmtj_trojan_grpc
  - rmtj_trojan_ws
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,Reject,REJECT
- RULE-SET,Games,BEST-PING
- MATCH,GLOBAL
external-ui: "/usr/share/openclash/ui"
sniffer:
  enable: true
  parse-pure-ip: true
tun:
  enable: true
  stack: system
  device: utun
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
authentication:
- Clash:xxxxxxx
rule-providers:
  Porn:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Reject.yaml"
    url: https://raw.githubusercontent.com/ayanagroup-official/openclash/main/rule_provider/Reject.yaml
    interval: 300
  Games:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Games.yaml"
    url: https://raw.githubusercontent.com/ayanagroup-official/openclash/main/game_rules/Games.yaml
    interval: 300
